import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Github Explorer",
  description: "Generated by john-papani",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16 bg-zinc-800 `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
